title: Mark (Hao) Chen blog
author: Mark (Hao) Chen

social-network-links:
  email: "a77069752@gmail.com"
  rss: true 
  github: hmarkc
  linkedin: www.linkedin.com/in/mark-hao-chen/

# How to display the link to your website in the footer
# Remove this if you don't want a link in the footer
url-pretty: "hmarkc.github.io/blog"
excerpt_length: 50
feed_show_excerpt: true
feed_show_tags: true
post_search: true
edit_page_button: false
navbar-var-length: false

navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
page-col: "#928585"
text-col: "#ffffff"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
